name: Master CI

on:
  push:
    branches: [master] 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the app
        run: g++ -std=c++17 *.cpp -o rpg
      - name: debugging
        run: g++ *.cpp -Wextra
      - name: debugging memory leak install
        run: sudo apt install valgrind
      - name: debugging cppcheck install
        run: sudo apt install cppcheck
      - name: debugging memory leak
        run: valgrind  --error-exitcode=1 ./a.out test/units/1.json test/units/2.json
      - name: style and performance test
        run: cppcheck *.cpp --enable=warning,style,performance --error-exitcode=1 &> styleAndPerformance.txt
      - name: Upload file
        uses: actions/upload-artifact@v1
        with:
          name: styleAndPerformance
          path: styleAndPerformance.txt
      - name: Get googletest
        run: |
              sudo apt install libgtest-dev
              sudo apt install cmake
              cd /usr/src/gtest
              sudo cmake CMakeLists.txt
              sudo make
              sudo ln -st /usr/lib/ /usr/src/gtest/libgtest.a
              sudo ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - name: Build unit tests
        run: |
              cd test
              cmake CMakeLists.txt
              make
      - name: Run unit tests
        run : |
              cd test
              ./runTests     