name: pushdocs.yml

on:
  push:
    branches:
    - jsonparser
    - gh-pages

jobs:
  deploy:
    name: Deploy to github pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get doxygen, and utils
      run: sudo apt-get install doxygen graphviz texlive-latex-extra
    - name: Create docs
      run: make docs    
    - name: Make pdf  
      run: |
        cd DOCS/latex
        make
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: DOCS/latex/refman.pdf


    - name: Push git subdir as branch
      uses: s0/git-publish-subdir-action@v2.4.0

      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: DOCS/html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}