name: Automated test CI

on:
  push:
    branches: [docker] 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: 97vix/moszekalmantest:3.0
    steps:
      - uses: actions/checkout@v2
      - name: Run all test
        run: make test
      - name: Upload file
        uses: actions/upload-artifact@v1
        with:
          name: styleAndPerformance
          path: styleAndPerformance.txt       
