name: Automated test CI

on:
  push:
    branches: [docker] 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: 97vix/moszekalmantest:2.0
    steps:
      - uses: actions/checkout@v2
      - name: Get googletest
        run: |
              cd /usr/src/gtest
              cmake CMakeLists.txt
              make .
              ln -st /usr/lib/ /usr/src/gtest/libgtest.a
              ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - name: Run all tests
        run: make test
      - name: Upload file
        uses: actions/upload-artifact@v1
        with:
          name: styleAndPerformance
          path: styleAndPerformance.txt       
